/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CENTRO_H_RPCGEN
#define _CENTRO_H_RPCGEN

#include <rpc/rpc.h>
#include "encomun.h"

#ifdef __cplusplus
extern "C" {
#endif

#define MAXLEN 512

typedef char *str;

struct datos {
	str nombre;
	str respuesta;
};
typedef struct datos datos;

// Para la lista de clientes (bombas)
typedef struct cliente{
    char nombre[128];    
    char desafio[256];    
    int tiempoVencimiento;
    struct cliente *siguiente;
} bomba;

char *nombreServidor;
int capacidadMaximaServidor; 
int tiempoEjecucionServidor;
int inventarioServidor;
int suministroServidor;
int tiempoRespuestaServidor;
bomba *listaBombas;
FILE *logServer;

#define CENTRO_PROG 0x23868011
#define CENTRO_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define SOLICITAR_DESAFIO 1
extern  char ** solicitar_desafio_1(datos *, CLIENT *);
extern  char ** solicitar_desafio_1_svc(datos *, struct svc_req *);
#define RESPODNDER_DESAFIO 2
extern  char ** respodnder_desafio_1(datos *, CLIENT *);
extern  char ** respodnder_desafio_1_svc(datos *, struct svc_req *);
#define SOLICITAR_TIEMPO 3
extern  int * solicitar_tiempo_1(char **, CLIENT *);
extern  int * solicitar_tiempo_1_svc(char **, struct svc_req *);
#define SOLICITAR_GASOLINA 4
extern  int * solicitar_gasolina_1(char **, CLIENT *);
extern  int * solicitar_gasolina_1_svc(char **, struct svc_req *);
extern int centro_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SOLICITAR_DESAFIO 1
extern  char ** solicitar_desafio_1();
extern  char ** solicitar_desafio_1_svc();
#define RESPODNDER_DESAFIO 2
extern  char ** respodnder_desafio_1();
extern  char ** respodnder_desafio_1_svc();
#define SOLICITAR_TIEMPO 3
extern  int * solicitar_tiempo_1();
extern  int * solicitar_tiempo_1_svc();
#define SOLICITAR_GASOLINA 4
extern  int * solicitar_gasolina_1();
extern  int * solicitar_gasolina_1_svc();
extern int centro_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_str (XDR *, str*);
extern  bool_t xdr_datos (XDR *, datos*);

#else /* K&R C */
extern bool_t xdr_str ();
extern bool_t xdr_datos ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CENTRO_H_RPCGEN */
